# Generated by Django 5.1.6 on 2025-03-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="registered_by",
            field=models.CharField(
                default="сам", max_length=255, verbose_name="Кем зарегистрирован"
            ),
        ),
    ]
